ALTER TABLE [dbo].[AlertType]
    ADD CONSTRAINT [PK_AlertType] PRIMARY KEY CLUSTERED ([AlertTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

