ALTER TABLE [dbo].[AccountsToProfiles]
    ADD CONSTRAINT [PK_AccountsToProfiles] PRIMARY KEY CLUSTERED ([AccountToProfileID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

