ALTER TABLE [dbo].[KeyCards]
    ADD CONSTRAINT [KeyCard] PRIMARY KEY CLUSTERED ([KeyCardID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);
