ALTER TABLE [dbo].[Lot]
    ADD CONSTRAINT [PK_Lot] PRIMARY KEY CLUSTERED ([LotID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

