ALTER TABLE [dbo].[ParkingInventory]
    ADD CONSTRAINT [PK_ParkingInventory] PRIMARY KEY CLUSTERED ([ParkingInventoryID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

