ALTER TABLE [dbo].[ParkingStallType]
    ADD CONSTRAINT [PK_ParkingStallType] PRIMARY KEY CLUSTERED ([ParkingStallTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

