ALTER TABLE [dbo].[ParkingStall]
    ADD CONSTRAINT [PK_ParkingStall] PRIMARY KEY CLUSTERED ([ParkingStallID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

