ALTER TABLE [UserProfile].[PhonesToProfiles]
	ADD CONSTRAINT [PK_PhonesToProfiles]
	PRIMARY KEY CLUSTERED ([PhonesToProfilesID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);
