ALTER TABLE [dbo].[zState]
    ADD CONSTRAINT [PK_zState] PRIMARY KEY CLUSTERED ([StateID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

