CREATE TABLE [dbo].[Building] (
    [BuildingID]         INT           IDENTITY (1, 1) NOT NULL,
    [BuildingName]       VARCHAR (256) NULL,
	[OwnerID]            INT    NULL,
    [ManagerID]          INT  NULL,
    [AddressID]          INT    NULL,
    [MailingAddressID]   INT  NULL,
	[PrimaryPhoneNumber] VARCHAR(20)    NULL,
	[PrimaryFaxNumber]   VARCHAR(20)    NULL,
	[MailingPhoneNumber] VARCHAR(20)    NULL,
	[MailingFaxNumber]   VARCHAR(20)    NULL,
	[BankName]			 NVARCHAR(50)    NULL,
	[AccountName]		 NVARCHAR(20)    NULL,
	[AccountNumber]      NVARCHAR(20)    NULL,
	[RoutingNumber]      NVARCHAR(20)    NULL,
	[Notes]				 NVARCHAR(256)   NULL,
	[TaxRate]			 DECIMAL(5,2)	 NULL,
	[DueDateReminder]	 INT			 NULL,
	[ReminderFrequency]	 INT			 NULL,
	[ReminderCutoff]	 INT			 NULL,
	[InvoiceCutoff]	     INT			 NULL,
	[ACHDiscountRate]	 DECIMAL(5,2)	 NULL,
	[CCDiscountRate]	 DECIMAL(5,2)	 NULL,
	[MontlyFee]			 DECIMAL(6,2)	 NULL,
	[MFBillingDay]		 INT        	 NULL,
	[VBNotification]     NVARCHAR(256)   NULL,
	[IsActive]           BIT             NOT NULL,
    [HasLots]            NCHAR (10)    NULL,
    [HasMultipleTenants] NCHAR (10)    NULL,
    [UpdatedDate]        DATETIME      NULL,
	[CreatedDate]        DATETIME      NULL
);

