ALTER TABLE [SecurityGroup].[SecurityRole]
    ADD CONSTRAINT [PK_SecurityRole] PRIMARY KEY CLUSTERED ([SecurityRoleID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

