ALTER TABLE [SecurityGroup].[SecurityGroup]
    ADD CONSTRAINT [PK_SecurityGroup] PRIMARY KEY CLUSTERED ([SecurityGroupID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

