ALTER TABLE [UserProfile].[OnlineCheckingType]
	ADD CONSTRAINT [PK_OnlineCheckingType] PRIMARY KEY CLUSTERED ([OnlineCheckingTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);
