ALTER TABLE [UserProfile].[UserProfileType]
    ADD CONSTRAINT [PK_UserProfileType] PRIMARY KEY CLUSTERED ([UserProfileTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

