ALTER TABLE [UserProfile].[UserProfileToCompany]
	ADD CONSTRAINT [PK_UserProfileToCompany]
	PRIMARY KEY CLUSTERED ([UserProfileToCompanyID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);
