ALTER TABLE [UserProfile].[UserProfileStatus]
    ADD CONSTRAINT [PK_UserProfileStatus] PRIMARY KEY CLUSTERED ([UserProfileStatusID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

