ALTER TABLE [UserProfile].[VehicleModel]
    ADD CONSTRAINT [PK_VehicleModel] PRIMARY KEY CLUSTERED ([VehicleModelID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

